### ISSUE TITLE
How I can setup initial tab bar item

### ISSUE THREAD

**Issue by nodahikaru** [azimin/AZTabBarController#1]
I need to setup selectedIndex=3 when tabbar controller shows initially. 
So I had changed self.selectedIndex=3 in viewDidLoad function of AZTabbarController.
Controller and view is 3rd controller and view, but tab bar item in Tabbar is still first item. 
How I can fix this problem?

**Comment by nodahikaru** [comment]
So it is useful using cocoa pods?

**Comment by azimin** [comment]
@rwh23 yes

**Comment by azimin** [comment]
Seems that https://github.com/azimin/AZTabBarController/pull/2 fixed this issue
